version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/src/Keda.Scaler.DurableTask.AzureStorage"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/tests/Keda.Scaler.WebJobs.DurableFunctions.Examples"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/actions/**"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/tests"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
